apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "default-chart.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "default-chart.labels" . | nindent 4 }}  
data:
{{ tpl (.Files.Get "env-vars.conf") $ | indent 2}}  