apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: goapi-postgres
spec:
  instances: 2
  storage:
    size: 1Gi
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: goapi_db
      owner: goapi_user
